.\" shorthand for double quote that works everywhere.
.ds q \N'34'
.TH intel_bios_dumper __appmansuffix__ __xorgversion__
.SH NAME
intel_bios_dumper \- Saves the Intel video BIOS contents to a file.
.SH SYNOPSIS
.B intel_bios_dumper \fIfilename\fR
.SH DESCRIPTION
.B intel_bios_dumper
is a tool to save the contents of the Intel video BIOS to a file.  It
can then be parsed offline for debugging issues with the video bios
table handling.
.SH SEE ALSO
.BR intel_bios_reader(1)
