.\" shorthand for double quote that works everywhere.
.ds q \N'34'
.TH intel_reg_snapshot __appmansuffix__ __xorgversion__
.SH NAME
intel_reg_snapshot \- Take a GPU register snapshot
.SH SYNOPSIS
.B intel_reg_snapshot
.SH DESCRIPTION
.B intel_reg_snapshot
takes a snapshot of the registers of an Intel GPU, and writes it to standard
output.  These files can be inspected later with the
.B intel_reg_dumper
tool.
.SH SEE ALSO
.BR intel_reg_dumper(1)
