.\" shorthand for double quote that works everywhere.
.ds q \N'34'
.TH intel_reg_dumper __appmansuffix__ __xorgversion__
.SH NAME
intel_reg_dumper \- Decode a bunch of Intel GPU registers for debugging
.SH SYNOPSIS
.B intel_reg_dumper [ options ] [ file ]
.SH DESCRIPTION
.B intel_reg_dumper
is a tool to read and decode the values of many Intel GPU registers.  It is
commonly used in debugging video mode setting issues.  If the
.B file
argument is present, the registers will be decoded from the given file
instead of the current registers.  Use the
.B intel_reg_snapshot
tool to generate such files.

When the
.B file
argument is present and the
.B -d
argument is not present,
.B intel_reg_dumper
will assume the file was generated on an Ironlake machine.
.SH OPTIONS
.TP
.B -d id
when a dump file is used, use 'id' as device id (in hex)
.TP
.B -h
prints a help message
.SH SEE ALSO
.BR intel_reg_snapshot(1)
