.\" shorthand for double quote that works everywhere.
.ds q \N'34'
.TH intel_audio_dump __appmansuffix__ __xorgversion__
.SH NAME
intel_audio_dump \- Dumps the Intel GPU registers for HDMI audio setup.
.SH SYNOPSIS
.B intel_audio_dump
.SH DESCRIPTION
.B intel_audio_dump
dumps and decodes registers containing the configuration of HDMI audio
handling on Intel GPUs.
