.\" shorthand for double quote that works everywhere.
.ds q \N'34'
.TH intel_reg_read __appmansuffix__ __xorgversion__
.SH NAME
intel_reg_read \- Reads an Intel GPU register value
.SH SYNOPSIS
.B intel_reg_read \fIregister\fR
.SH DESCRIPTION
.B intel_reg_read
is a tool to read Intel GPU registers, for use in debugging.  The
\fIregister\fR argument is given as hexadecimal.
.SH EXAMPLES
.TP
intel_reg_read 0x61230
Shows the register value for the first internal panel fitter.
