.\" shorthand for double quote that works everywhere.
.ds q \N'34'
.TH intel_gpu_dump 1 "intel_gpu_dump 1.0"
.SH NAME
intel_gpu_dump \- Print out debugging information on the state of the
Intel GPU.
.SH SYNOPSIS
.nf
.B intel_gpu_dump
.B intel_gpu_dump [ filename ]
.fi
.SH DESCRIPTION
.B intel_gpu_dump
is a tool to log the current state of an Intel GPU
when it is hung, for later analysis.  It requires kernel 2.6.30rc1 or newer,
debugfs mounted on /sys/kernel/debug or /debug, and root privilege for
mapping the device to inspect it.
.SS Options
.TP
.B filename
Decodes just one batchbuffer or ringbuffer dump, rather than dumping all
of the GPU state.
