.\" shorthand for double quote that works everywhere.
.ds q \N'34'
.TH intel_stepping __appmansuffix__ __xorgversion__
.SH NAME
intel_stepping \- Display the stepping information for an Intel GPU
.SH SYNOPSIS
.B intel_stepping
.SH DESCRIPTION
.B intel_stepping
is a tool to print the stepping information for an Intel GPU, along with
the PCI ID and revision used to determine it.
It requires root privilege to map the graphics device.
.SH BUGS
Not all the known stepping IDs or chipsets are included, so the output
on some devices may not be as specific as possible.
