.\" shorthand for double quote that works everywhere.
.ds q \N'34'
.TH intel_gtt __appmansuffix__ __xorgversion__
.SH NAME
intel_gtt \- Dump the contents of an Intel GPU's GTT
.SH SYNOPSIS
.B intel_gtt
.SH DESCRIPTION
.B intel_gtt
is a tool to view the contents of the GTT on an Intel GPU.  The GTT is
the page table that maps between GPU addresses and system memory.
This tool can be useful in debugging the Linux AGP driver
initialization of the chip or in debugging later overwriting of the
GTT with garbage data.
