.\" shorthand for double quote that works everywhere.
.ds q \N'34'
.TH intel_reg_write __appmansuffix__ __xorgversion__
.SH NAME
intel_reg_write \- Set an Intel GPU register to a value
.SH SYNOPSIS
.B intel_reg_write \fIregister\fR \fIvalue\fR
.SH DESCRIPTION
.B intel_reg_write
is a tool to set Intel GPU registers to values, for use in speeding up
debugging.  The \fIregister\fR and \fIvalue\fR arguments are given as
hexadecimal.
.SH EXAMPLES
.TP
intel_reg_write 0x61230 0x0
Disables the first internal panel fitter.
