.\" shorthand for double quote that works everywhere.
.ds q \N'34'
.TH intel_upload_blit_large_gtt __appmansuffix__ __xorgversion__
.SH NAME
intel_upload_blit_large_gtt \- microbenchmark of Intel GPU performance
.SH SYNOPSIS
.nf
.B intel_upload_blit_large_gtt
.fi
.SH DESCRIPTION
.B intel_upload_blit_large_gtt
is a microbenchmark tool for DRM performance.  It should be run with kernel
modesetting enabled, and may require root privilege for correct operation.
It does not require X to be running.
.PP
Given that it is a microbenchmark, its utility is largely for regression
testing of the kernel, and not for general conclusions on graphics
performance.
