.\" shorthand for double quote that works everywhere.
.ds q \N'34'
.TH intel_bios_reader __appmansuffix__ __xorgversion__
.SH NAME
intel_bios_reader \- Parses an Intel BIOS and displays many of its tables
.SH SYNOPSIS
.B intel_bios_reader \fIfilename\fR
.SH DESCRIPTION
.B intel_bios_reader
is a tool to parse the contents of an Intel video BIOS file.  The file
can come from intel_bios_dumper.  This can be used for quick debugging
of video bios table handling, which is harder when done inside of the
kernel graphics driver.
.SH SEE ALSO
.BR intel_bios_dumper (1)
