.\" shorthand for double quote that works everywhere.
.ds q \N'34'
.TH intel_lid __appmansuffix__ __xorgversion__
.SH NAME
intel_lid \- Polls the values of different reports about laptop lid state.
.SH SYNOPSIS
.B intel_lid
.SH DESCRIPTION
.B intel_lid
is a tool to poll ACPI and the BIOS scratch register's reporting of
laptop lid state.  This can be used for debugging issues with laptop
modesetting for lid opening and closing.
