#!/bin/sh
#
# This check if we can crash the kernel with segmentation-fault
# by reading /sys/kernel/debug/dri/0/i915_emon_status too quickly
#

. ./drm_lib.sh

for z in $(seq 1 1000); do
	cat $i915_path/i915_emon_status > /dev/null
done

# If we got here, we haven't crashed

exit 0
