#!/bin/bash

if ! find /sys/class/drm/card*/ | grep l3_parity > /dev/null ; then
	echo "no l3_parity interface, skipping test"
	exit 77
fi

SOURCE_DIR="$( dirname "${BASH_SOURCE[0]}" )"
. $SOURCE_DIR/drm_lib.sh

$SOURCE_DIR/../tools/intel_l3_parity -c

#Check that we can remap a row
$SOURCE_DIR/../tools/intel_l3_parity 0,0,0
disabled=`$SOURCE_DIR/../tools/intel_l3_parity | grep -c 'Row 0, Bank 0, Subbank 0 is disabled'`
if [ "$disabled" != "1" ] ; then
	echo "Fail"
	exit 1
fi

$SOURCE_DIR/../tools/intel_l3_parity -c

#Check that we can clear remaps
if [ `$SOURCE_DIR/../tools/intel_l3_parity | wc -c` != "0" ] ; then
	echo "Fail"
	exit 1
fi
