#!/bin/bash
# Test some of the most critical tools we have accidentally broken before.
# TODO: Possibly make tests parse output

SOURCE_DIR="$( dirname "${BASH_SOURCE[0]}" )"
. $SOURCE_DIR/drm_lib.sh

# ARB_MODE has existed for many gens
PATH=$SOURCE_DIR/../tools:$PATH
do_or_die "intel_reg_read 0x4030"
do_or_die "intel_reg_dumper"

# TODO: Add more tests

exit $IGT_EXIT_SUCCESS

