#ifndef GEN9_RENDER_H
#define GEN9_RENDER_H

#include "gen8_render.h"

#define GEN7_3DSTATE_VF				GEN6_3D(3, 0, 0x0c)
#define GEN9_3DSTATE_COMPONENT_PACKING		GEN6_3D(3, 0, 0x55)

#define GEN9_SBE_ACTIVE_COMPONENT_NONE		0
#define GEN9_SBE_ACTIVE_COMPONENT_XY		1
#define GEN9_SBE_ACTIVE_COMPONENT_XYZ		2
#define GEN9_SBE_ACTIVE_COMPONENT_XYZW		3

#define GEN9_PIPELINE_SELECTION_MASK		(3 << 8)
#define GEN9_PIPELINE_SELECT			(GEN6_3D(1, 1, 4) | (3 << 8))

#endif
