check_PROGRAMS = \
	igt_no_exit \
	igt_no_exit_list_only \
	igt_fork_helper \
	igt_list_only \
	igt_no_subtest \
	igt_simulation \
	$(NULL)

check_SCRIPTS = \
	igt_command_line.sh \
	$(NULL)

TESTS = \
	$(check_PROGRAMS) \
	$(check_SCRIPTS) \
	$(NULL)

# Test that exercise specific asserts in the test framework library and are
# hence expected to fail.
XFAIL_TESTS = \
	igt_no_exit \
	igt_no_exit_list_only \
	igt_no_subtest \
	$(NULL)
